/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AuthorUpdateManyWithoutPostsInput } from "./AuthorUpdateManyWithoutPostsInput";
import { ValidateNested, IsOptional, IsBoolean, IsDate } from "class-validator";
import { Type } from "class-transformer";
import { CategoryWhereUniqueInput } from "../../category/base/CategoryWhereUniqueInput";
import { TagUpdateManyWithoutPostsInput } from "./TagUpdateManyWithoutPostsInput";
import { IsJSONValue } from "@app/custom-validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";

@InputType()
class PostUpdateInput {
  @ApiProperty({
    required: false,
    type: () => AuthorUpdateManyWithoutPostsInput,
  })
  @ValidateNested()
  @Type(() => AuthorUpdateManyWithoutPostsInput)
  @IsOptional()
  @Field(() => AuthorUpdateManyWithoutPostsInput, {
    nullable: true,
  })
  author?: AuthorUpdateManyWithoutPostsInput;

  @ApiProperty({
    required: false,
    type: () => CategoryWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CategoryWhereUniqueInput)
  @IsOptional()
  @Field(() => CategoryWhereUniqueInput, {
    nullable: true,
  })
  category?: CategoryWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  enabled?: boolean | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  publishedAt?: Date | null;

  @ApiProperty({
    required: false,
    type: () => TagUpdateManyWithoutPostsInput,
  })
  @ValidateNested()
  @Type(() => TagUpdateManyWithoutPostsInput)
  @IsOptional()
  @Field(() => TagUpdateManyWithoutPostsInput, {
    nullable: true,
  })
  tag?: TagUpdateManyWithoutPostsInput;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  title?: InputJsonValue;
}

export { PostUpdateInput as PostUpdateInput };
