/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateSubCategoryArgs } from "./CreateSubCategoryArgs";
import { UpdateSubCategoryArgs } from "./UpdateSubCategoryArgs";
import { DeleteSubCategoryArgs } from "./DeleteSubCategoryArgs";
import { SubCategoryFindManyArgs } from "./SubCategoryFindManyArgs";
import { SubCategoryFindUniqueArgs } from "./SubCategoryFindUniqueArgs";
import { SubCategory } from "./SubCategory";
import { SubCategoryService } from "../subCategory.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => SubCategory)
export class SubCategoryResolverBase {
  constructor(
    protected readonly service: SubCategoryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "SubCategory",
    action: "read",
    possession: "any",
  })
  async _subCategoriesMeta(
    @graphql.Args() args: SubCategoryFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [SubCategory])
  @nestAccessControl.UseRoles({
    resource: "SubCategory",
    action: "read",
    possession: "any",
  })
  async subCategories(
    @graphql.Args() args: SubCategoryFindManyArgs
  ): Promise<SubCategory[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => SubCategory, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "SubCategory",
    action: "read",
    possession: "own",
  })
  async subCategory(
    @graphql.Args() args: SubCategoryFindUniqueArgs
  ): Promise<SubCategory | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => SubCategory)
  @nestAccessControl.UseRoles({
    resource: "SubCategory",
    action: "create",
    possession: "any",
  })
  async createSubCategory(
    @graphql.Args() args: CreateSubCategoryArgs
  ): Promise<SubCategory> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => SubCategory)
  @nestAccessControl.UseRoles({
    resource: "SubCategory",
    action: "update",
    possession: "any",
  })
  async updateSubCategory(
    @graphql.Args() args: UpdateSubCategoryArgs
  ): Promise<SubCategory | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => SubCategory)
  @nestAccessControl.UseRoles({
    resource: "SubCategory",
    action: "delete",
    possession: "any",
  })
  async deleteSubCategory(
    @graphql.Args() args: DeleteSubCategoryArgs
  ): Promise<SubCategory | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
